Lagt til sluttidspunkt på arrangement
Project-insert-name/root-website pull request #123
Opened 2024-02-05 20:03 UTC by emberal

Lagt inn mulighet til å sette sluttid på et arrangement.
- Sluttiden må komme etter starttiden
- Arrangementer vil vises som kommende helt til sluttiden er gått ut, dersom det er definert.
- Ics filer vil bruke sluttiden dersom det er definert, eller settes varighet til 2 timer.

closing #114

2024-02-06 18:56 UTC, 594760 commented
![image](https://github.com/Project-insert-name/root-website/assets/89256648/ff92aaf0-9a44-49b0-bb34-c8c59c178b46)

Når jeg tester funker det ikke local host

2024-02-07 08:18 UTC, 594760 requested changes

2024-02-07 08:54 UTC, emberal commented on app/(root)/arrangement/[slug]/page.tsx
> +    const end = event.end_time ? { end: toDateTuple(event.end_time) } : { duration: { hours: 2 } }
Tenkte på det, men usikker på hvordan det kan gjøres når det er et date time object. En mulig løsning kan være å vise alle arrangementer for hele dagen på, kommendd

2024-02-07 08:54 UTC, emberal commented
> ![image](https://github.com/Project-insert-name/root-website/assets/89256648/ff92aaf0-9a44-49b0-bb34-c8c59c178b46)
> 
> Når jeg tester funker det ikke localhost

Hva virker ikke?

2024-02-07 13:56 UTC, 594760 commented
> > ![image](https://private-user-images.githubusercontent.com/89256648/302745397-ff92aaf0-9a44-49b0-bb34-c8c59c178b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTY0MzgsIm5iZiI6MTcwNzI5NjEzOCwicGF0aCI6Ii84OTI1NjY0OC8zMDI3NDUzOTctZmY5MmFhZjAtOWE0NC00OWIwLWJiMzQtYzhjNTljMTc4YjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA4NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NjgzMWQ2OWFmZmUwZWU2MzBhMmI4YTFiYzFjYjBmZGY3NzhhN2VkNGQ1ZDNkYzNmZjIyMjAwNGYyZTkzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mN5Ru1SkgUeVvKSyQXR-wtFfi_-qYOBId6kFVTr_0Xk)
> > Når jeg tester funker det ikke localhost
> 
> Hva virker ikke?

Det blir gjort til et tidligere arrangement før 2 timer etter start tidspunkt. Når slutttidspunkt ikke er satt.

2024-02-07 16:51 UTC, emberal commented
Har ikke gjort noe med starttiden. Dersom sluttiden ikke er definert, så er det som før. Kan se om det er mulig å legge på 2 timer i groq, men tror ikke det. Men vil tro det kan være mulig å konvertere det til kun dato, slik at arrangementet vises hele dagen

2024-02-11 15:37 UTC, 594760 commented
Kan vi ikke da bare hente ut alle arrangement og sorter de ut tidligere og kommende arrangement med typescript jeg kan se på det og komme med et forslag.

2024-02-11 20:44 UTC, 594760 commented
> Har ikke gjort noe med starttiden. Dersom sluttiden ikke er definert, så er det som før. Kan se om det er mulig å legge på 2 timer i groq, men tror ikke det. Men vil tro det kan være mulig å konvertere det til kun dato, slik at arrangementet vises hele dagen

Vil jo ikke hvis det for hele dagen. En user storien er at man er litt sent til arangemanget og skal inn å sjekke hvor det er så forvinner det fra framsiden minutte arangemanget starter. Så blir overkill å ha det hele dagen.

2024-02-11 22:40 UTC, emberal commented
Fant en rimlig lett løsning på det nå🫠
```ts
): Promise<ReadonlyArray<RootEvent>> {
    const date = new Date()
    date.setHours(date.getHours() - 2)
    return cdnClient.fetch(
        '*[_type == "event" && (defined(end_time) && end_time >= now() || start_time >= $now)) && start_time > $last_start_time] | order(start_time asc)[0...$limit]',
        {
            limit,
            last_start_time: lastStartTime,
            now: date.toISOString(),
        },
    )
}
```

2024-02-14 09:42 UTC, 594760 approved these changes
Funker så langt jeg har sett

2024-02-14 09:42 UTC, merged