Om oss side
Project-insert-name/root-website pull request #78
Opened 2024-01-12 14:37 UTC by 594760

2024-01-15 16:44 UTC, emberal requested changes
Ser bra ut.
Det meste jeg kommenterte er ikke så viktig, men gjerne formater koden med prettier. Det kan gjøres med en kommando, som du kan se i package json filen

2024-01-15 16:46 UTC, emberal commented on app/(root)/om-oss/page.tsx
> +export const dynamic = "force-dynamic" //TODO Må den være her
Trengs vel egentlig ikke her. Det er bare for å slå av caching fra next. Men det er ikke så farlig om innholdet i denne siden blir cachet

2024-01-15 17:54 UTC, 594760 commented on components/omOss/sideNavigator.tsx
> +        <Link key={infoPage._id} className={`text-start text-2xl p-2 hover:text-rootBlueDark`} href={`om-oss#${infoPage._id}`} >
Grunnen for at jeg valgte den var at den er unik

2024-01-15 22:47 UTC, 594760 commented on components/omOss/InfoPageContent.tsx
> +    const [menuOpen, setMenuOpen] = useState(false)
Hva er fordelen med å bruke useToggle hook over useState?

2024-01-16 16:24 UTC, emberal commented on components/omOss/InfoPageContent.tsx
> +    const [menuOpen, setMenuOpen] = useState(false)
Bare at du slipper å sette verdien til det motsatte, den wrapper bare useState

2024-01-16 16:25 UTC, emberal approved these changes

2024-01-16 16:25 UTC, merged