Gallery modal
Project-insert-name/root-website pull request #85
Opened 2024-01-21 12:20 UTC by simsine

Galleri modal fungerer nå som den skal. Ta gjerne en titt om dere ønsker

2024-01-21 14:37 UTC, 594760 reviewed
Det funker ikke vær gang jeg åpner et bilde.  Kasnje man kan bruke react-use-keypress istedenfor. https://vercel.com/templates/next.js/image-gallery-starter

2024-01-21 19:13 UTC, emberal commented
> Det funker ikke vær gang jeg åpner et bilde. Kasnje man kan bruke react-use-keypress istedenfor useEffect biten vet ikke om det hjelper noe men blir værtfall litt mere lesbar kode. https://vercel.com/templates/next.js/image-gallery-starter

Alt ser ut til å virke som det skal for meg. Har testet både i chrome, firefox og duckduckgo

2024-01-21 19:18 UTC, emberal approved these changes
Ser bra ut.

Noen ting som det kan være lurt å se på er
- Gjøre tilbake knappen på mobil lavere. Nå tar den opp circa halve skjermen.
- Når man åpner modal på mobil så scroller den alltid opp, og ned igjen når man lukker det.
- Vise i modal at det er mulig og navigere. For eksempel er det mulig å bruke [keyboard](https://nextui.org/docs/components/kbd#usage) fra nextui for eksempel.

2024-01-22 11:02 UTC, emberal requested changes
Navigering med piltastene funker ikke alltid på første render: http://localhost:3000/galleri/test
- Dersom man velger første bilde virker det ikke å navigere, men dersom man velger noen av de andre så virker det. Deretter virker det på første igjen.

Modal ligger bak header dersom bilde er stort.
Kan fikses ved å sette z til høyere enn header- og kanskje sette maks størrelse for å få litt rom.

2024-01-22 11:03 UTC, emberal commented
Andre ting som kan være verdt å se på. Må ikke fikses til denne pull requesten.

- Trykk på esc for å lukke modal
- Swipe på telefon for å paginere
- Tilbake på mobil lukker modal i stedet for å navigere til forrige side

2024-01-23 17:30 UTC, 594760 commented
Er det bare meg eller funker det ikke å tab igjennom bildene? 
Det funker å tab igjennom de forskjellige galleriene.

2024-01-23 19:08 UTC, emberal commented
> Er det bare meg eller funker det ikke å tab igjennom bildene? Det funker å tab igjennom de forskjellige galleriene.

Tabbing funker, men det er ikke tydlig markert. Bildene mangler også focus styling. Ser ikke ut som det er mulig å åpne bildene med enter da

2024-01-23 19:58 UTC, emberal approved these changes
Tror det skal være greit til å merges nå.
Mer funksjonalitet kan legges til etterhvert

2024-01-24 18:09 UTC, merged